[package]
name = "kvs"
version = "0.1.0"
authors = ["Alec Di Vito <divito.alec@gmail.com>"]
description = "A key value store in rust"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.32.0"
structopt = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
log = "0.4.6"
env_logger = "0.6.1"
sled = "0.22.1"

[dev-dependencies]
assert_cmd = "0.11.0"
criterion = "0.2.11"
predicates = "1.0.0"
rand = "0.6.5"
tempfile = "3.0.7"
walkdir = "2.2.7"

[[bench]]
name = "engine_bench"
harness = false